### ISSUE TITLE
Possibility of a Universal App version

### ISSUE THREAD

**Issue by assad62** [zinkpad/SharpCifs#1]
Hi,

First of all many thanks for taking the time to port jcifs to C#. As expected this works very well in WP8.1 silverlight apps, however I  was wondering if you can look into having a Universal App version as well. 

Right now If I use the dll in a universal app I get the following error:
Cannot find type System.Security.Cryptography.HashAlgorithm in module mscorlib.dll. 

I am guessing this is happening because System.security isnt available in UWP. 

Regards

**Comment by zinkpad** [comment]
Hi,

Unfortunately you cannot use SharpCifs in Universal Apps without make a lot of changes (sockets, threading,...), check this: https://msdn.microsoft.com/en-us/library/windows/apps/mt149137.aspx

I don't discard to port the code in sometime, but not shortly.

Regards!
